# The manifest for the "app3copilot-main" pipeline.
# This YAML file defines your pipeline: the source repository it tracks and the order of the environments to deploy to.
# For more info: https://aws.github.io/copilot-cli/docs/manifest/pipeline/

# The name of the pipeline.
name: app3copilot-main

# The version of the schema used in this template.
version: 1

# This section defines your source, changes to which trigger your pipeline.
source:
  # The name of the provider that is used to store the source artifacts.
  # (i.e. GitHub, Bitbucket, CodeCommit)
  provider: GitHub
  # Additional properties that further specify the location of the artifacts.
  properties:
    branch: main
    repository: https://github.com/milunadev/app3Copilot
    # Optional: specify the name of an existing CodeStar Connections connection.
    # connection_name: a-connection

# This section defines the order of the environments your pipeline will deploy to.
stages:
  - name: test
    test_commands: 
      - export SERVICE_URL=$(aws elbv2 describe-load-balancers --names app3-t-Publi-dLvD85G1HMIM --query 'LoadBalancers[0].DNSName' --output text)
      - echo "Service URL: $SERVICE_URL"
      - echo "ls $CODEBUILD_SRC_DIR/copilot/pipelines/app3copilot-main"
      - echo "Ejecutando todas las pruebas"
      - ./$CODEBUILD_SRC_DIR/copilot/pipelines/app3copilot-main/test_website.sh $SERVICE_URL
    # requires_approval: true
    # test_commands: [echo 'running tests', make test]

